package com.zy17.douban.bean;

import static org.junit.Assert.*;

import org.junit.Test;

import static org.hamcrest.Matchers.*;

import com.alibaba.fastjson.JSON;

/**
 * Created by zhangyan53 on 2016/3/18.
 */
public class UsBoxResultTest {
    @Test
    public void jsonTest() {
        UsBoxResult usBoxResult = JSON.parseObject(json, UsBoxResult.class);
        assertThat(usBoxResult.getSubjects().size(), greaterThan(0));
    }

    public String json = "{\n"
            + "    \"date\": \"3月11日 - 3月13日\",\n"
            + "    \"subjects\": [\n"
            + "        {\n"
            + "            \"box\": 50000000,\n"
            + "            \"new\": false,\n"
            + "            \"rank\": 1,\n"
            + "            \"subject\": {\n"
            + "                \"rating\": {\n"
            + "                    \"max\": 10,\n"
            + "                    \"average\": 9.3,\n"
            + "                    \"stars\": \"50\",\n"
            + "                    \"min\": 0\n"
            + "                },\n"
            + "                \"genres\": [\n"
            + "                    \"喜剧\",\n"
            + "                    \"动作\",\n"
            + "                    \"动画\"\n"
            + "                ],\n"
            + "                \"title\": \"疯狂动物城\",\n"
            + "                \"casts\": [\n"
            + "                    {\n"
            + "                        \"alt\": \"http://movie.douban.com/celebrity/1017930/\",\n"
            + "                        \"avatars\": {\n"
            + "                            \"small\": \"https://img3.doubanio.com/img/celebrity/small/4815.jpg\",\n"
            + "                            \"large\": \"https://img3.doubanio.com/img/celebrity/large/4815.jpg\",\n"
            + "                            \"medium\": \"https://img3.doubanio.com/img/celebrity/medium/4815.jpg\"\n"
            + "                        },\n"
            + "                        \"name\": \"金妮弗·古德温\",\n"
            + "                        \"id\": \"1017930\"\n"
            + "                    },\n"
            + "                    {\n"
            + "                        \"alt\": \"http://movie.douban.com/celebrity/1013760/\",\n"
            + "                        \"avatars\": {\n"
            + "                            \"small\": \"https://img1.doubanio.com/img/celebrity/small/18772.jpg\",\n"
            + "                            \"large\": \"https://img1.doubanio.com/img/celebrity/large/18772.jpg\",\n"
            + "                            \"medium\": \"https://img1.doubanio.com/img/celebrity/medium/18772.jpg\"\n"
            + "                        },\n"
            + "                        \"name\": \"杰森·贝特曼\",\n"
            + "                        \"id\": \"1013760\"\n"
            + "                    },\n"
            + "                    {\n"
            + "                        \"alt\": \"http://movie.douban.com/celebrity/1049501/\",\n"
            + "                        \"avatars\": {\n"
            + "                            \"small\": \"https://img3.doubanio.com/img/celebrity/small/1410696326.11"
            + ".jpg\",\n"
            + "                            \"large\": \"https://img3.doubanio.com/img/celebrity/large/1410696326.11"
            + ".jpg\",\n"
            + "                            \"medium\": \"https://img3.doubanio.com/img/celebrity/medium/1410696326.11"
            + ".jpg\"\n"
            + "                        },\n"
            + "                        \"name\": \"伊德里斯·艾尔巴\",\n"
            + "                        \"id\": \"1049501\"\n"
            + "                    }\n"
            + "                ],\n"
            + "                \"collect_count\": 205388,\n"
            + "                \"original_title\": \"Zootopia\",\n"
            + "                \"subtype\": \"movie\",\n"
            + "                \"directors\": [\n"
            + "                    {\n"
            + "                        \"alt\": \"http://movie.douban.com/celebrity/1286985/\",\n"
            + "                        \"avatars\": {\n"
            + "                            \"small\": \"https://img1.doubanio.com/img/celebrity/small/1457505519.94"
            + ".jpg\",\n"
            + "                            \"large\": \"https://img1.doubanio.com/img/celebrity/large/1457505519.94"
            + ".jpg\",\n"
            + "                            \"medium\": \"https://img1.doubanio.com/img/celebrity/medium/1457505519.94"
            + ".jpg\"\n"
            + "                        },\n"
            + "                        \"name\": \"拜伦·霍华德\",\n"
            + "                        \"id\": \"1286985\"\n"
            + "                    },\n"
            + "                    {\n"
            + "                        \"alt\": \"http://movie.douban.com/celebrity/1324037/\",\n"
            + "                        \"avatars\": {\n"
            + "                            \"small\": \"https://img1.doubanio.com/img/celebrity/small/1456810684.78"
            + ".jpg\",\n"
            + "                            \"large\": \"https://img1.doubanio.com/img/celebrity/large/1456810684.78"
            + ".jpg\",\n"
            + "                            \"medium\": \"https://img1.doubanio.com/img/celebrity/medium/1456810684.78"
            + ".jpg\"\n"
            + "                        },\n"
            + "                        \"name\": \"瑞奇·摩尔\",\n"
            + "                        \"id\": \"1324037\"\n"
            + "                    },\n"
            + "                    {\n"
            + "                        \"alt\": \"http://movie.douban.com/celebrity/1304069/\",\n"
            + "                        \"avatars\": {\n"
            + "                            \"small\": \"https://img3.doubanio.com/img/celebrity/small/1456810614.66"
            + ".jpg\",\n"
            + "                            \"large\": \"https://img3.doubanio.com/img/celebrity/large/1456810614.66"
            + ".jpg\",\n"
            + "                            \"medium\": \"https://img3.doubanio.com/img/celebrity/medium/1456810614.66"
            + ".jpg\"\n"
            + "                        },\n"
            + "                        \"name\": \"杰拉德·布什\",\n"
            + "                        \"id\": \"1304069\"\n"
            + "                    }\n"
            + "                ],\n"
            + "                \"year\": \"2016\",\n"
            + "                \"images\": {\n"
            + "                    \"small\": \"https://img1.doubanio"
            + ".com/view/movie_poster_cover/ipst/public/p2315672647.jpg\",\n"
            + "                    \"large\": \"https://img1.doubanio"
            + ".com/view/movie_poster_cover/lpst/public/p2315672647.jpg\",\n"
            + "                    \"medium\": \"https://img1.doubanio"
            + ".com/view/movie_poster_cover/spst/public/p2315672647.jpg\"\n"
            + "                },\n"
            + "                \"alt\": \"http://movie.douban.com/subject/25662329/\",\n"
            + "                \"id\": \"25662329\"\n"
            + "            }\n"
            + "        },\n"
            + "        {\n"
            + "            \"box\": 25200000,\n"
            + "            \"new\": true,\n"
            + "            \"rank\": 2,\n"
            + "            \"subject\": {\n"
            + "                \"rating\": {\n"
            + "                    \"max\": 10,\n"
            + "                    \"average\": 7.7,\n"
            + "                    \"stars\": \"40\",\n"
            + "                    \"min\": 0\n"
            + "                },\n"
            + "                \"genres\": [\n"
            + "                    \"动作\",\n"
            + "                    \"悬疑\",\n"
            + "                    \"科幻\"\n"
            + "                ],\n"
            + "                \"title\": \"科洛弗道10号\",\n"
            + "                \"casts\": [\n"
            + "                    {\n"
            + "                        \"alt\": \"http://movie.douban.com/celebrity/1017898/\",\n"
            + "                        \"avatars\": {\n"
            + "                            \"small\": \"https://img3.doubanio.com/img/celebrity/small/1360912229.81"
            + ".jpg\",\n"
            + "                            \"large\": \"https://img3.doubanio.com/img/celebrity/large/1360912229.81"
            + ".jpg\",\n"
            + "                            \"medium\": \"https://img3.doubanio.com/img/celebrity/medium/1360912229.81"
            + ".jpg\"\n"
            + "                        },\n"
            + "                        \"name\": \"约翰·古德曼\",\n"
            + "                        \"id\": \"1017898\"\n"
            + "                    },\n"
            + "                    {\n"
            + "                        \"alt\": \"http://movie.douban.com/celebrity/1041018/\",\n"
            + "                        \"avatars\": {\n"
            + "                            \"small\": \"https://img1.doubanio.com/img/celebrity/small/32684.jpg\",\n"
            + "                            \"large\": \"https://img1.doubanio.com/img/celebrity/large/32684.jpg\",\n"
            + "                            \"medium\": \"https://img1.doubanio.com/img/celebrity/medium/32684.jpg\"\n"
            + "                        },\n"
            + "                        \"name\": \"玛丽·伊丽莎白·温斯特德\",\n"
            + "                        \"id\": \"1041018\"\n"
            + "                    },\n"
            + "                    {\n"
            + "                        \"alt\": \"http://movie.douban.com/celebrity/1018165/\",\n"
            + "                        \"avatars\": {\n"
            + "                            \"small\": \"https://img1.doubanio.com/img/celebrity/small/50687.jpg\",\n"
            + "                            \"large\": \"https://img1.doubanio.com/img/celebrity/large/50687.jpg\",\n"
            + "                            \"medium\": \"https://img1.doubanio.com/img/celebrity/medium/50687.jpg\"\n"
            + "                        },\n"
            + "                        \"name\": \"小约翰·加拉赫\",\n"
            + "                        \"id\": \"1018165\"\n"
            + "                    }\n"
            + "                ],\n"
            + "                \"collect_count\": 533,\n"
            + "                \"original_title\": \"10 Cloverfield Lane\",\n"
            + "                \"subtype\": \"movie\",\n"
            + "                \"directors\": [\n"
            + "                    {\n"
            + "                        \"alt\": \"http://movie.douban.com/celebrity/1354103/\",\n"
            + "                        \"avatars\": {\n"
            + "                            \"small\": \"https://img1.doubanio.com/img/celebrity/small/1458023591.47"
            + ".jpg\",\n"
            + "                            \"large\": \"https://img1.doubanio.com/img/celebrity/large/1458023591.47"
            + ".jpg\",\n"
            + "                            \"medium\": \"https://img1.doubanio.com/img/celebrity/medium/1458023591.47"
            + ".jpg\"\n"
            + "                        },\n"
            + "                        \"name\": \"丹·特拉亨伯格\",\n"
            + "                        \"id\": \"1354103\"\n"
            + "                    }\n"
            + "                ],\n"
            + "                \"year\": \"2016\",\n"
            + "                \"images\": {\n"
            + "                    \"small\": \"https://img1.doubanio"
            + ".com/view/movie_poster_cover/ipst/public/p2310097289.jpg\",\n"
            + "                    \"large\": \"https://img1.doubanio"
            + ".com/view/movie_poster_cover/lpst/public/p2310097289.jpg\",\n"
            + "                    \"medium\": \"https://img1.doubanio"
            + ".com/view/movie_poster_cover/spst/public/p2310097289.jpg\"\n"
            + "                },\n"
            + "                \"alt\": \"http://movie.douban.com/subject/2977957/\",\n"
            + "                \"id\": \"2977957\"\n"
            + "            }\n"
            + "        },\n"
            + "        {\n"
            + "            \"box\": 10800000,\n"
            + "            \"new\": false,\n"
            + "            \"rank\": 3,\n"
            + "            \"subject\": {\n"
            + "                \"rating\": {\n"
            + "                    \"max\": 10,\n"
            + "                    \"average\": 8,\n"
            + "                    \"stars\": \"40\",\n"
            + "                    \"min\": 0\n"
            + "                },\n"
            + "                \"genres\": [\n"
            + "                    \"喜剧\",\n"
            + "                    \"动作\",\n"
            + "                    \"科幻\"\n"
            + "                ],\n"
            + "                \"title\": \"死侍\",\n"
            + "                \"casts\": [\n"
            + "                    {\n"
            + "                        \"alt\": \"http://movie.douban.com/celebrity/1053623/\",\n"
            + "                        \"avatars\": {\n"
            + "                            \"small\": \"https://img1.doubanio.com/img/celebrity/small/48608.jpg\",\n"
            + "                            \"large\": \"https://img1.doubanio.com/img/celebrity/large/48608.jpg\",\n"
            + "                            \"medium\": \"https://img1.doubanio.com/img/celebrity/medium/48608.jpg\"\n"
            + "                        },\n"
            + "                        \"name\": \"瑞恩·雷诺兹\",\n"
            + "                        \"id\": \"1053623\"\n"
            + "                    },\n"
            + "                    {\n"
            + "                        \"alt\": \"http://movie.douban.com/celebrity/1017908/\",\n"
            + "                        \"avatars\": {\n"
            + "                            \"small\": \"https://img3.doubanio.com/img/celebrity/small/8515.jpg\",\n"
            + "                            \"large\": \"https://img3.doubanio.com/img/celebrity/large/8515.jpg\",\n"
            + "                            \"medium\": \"https://img3.doubanio.com/img/celebrity/medium/8515.jpg\"\n"
            + "                        },\n"
            + "                        \"name\": \"莫蕾娜·巴卡林\",\n"
            + "                        \"id\": \"1017908\"\n"
            + "                    },\n"
            + "                    {\n"
            + "                        \"alt\": \"http://movie.douban.com/celebrity/1329130/\",\n"
            + "                        \"avatars\": {\n"
            + "                            \"small\": \"https://img1.doubanio.com/img/celebrity/small/1370589932.99"
            + ".jpg\",\n"
            + "                            \"large\": \"https://img1.doubanio.com/img/celebrity/large/1370589932.99"
            + ".jpg\",\n"
            + "                            \"medium\": \"https://img1.doubanio.com/img/celebrity/medium/1370589932.99"
            + ".jpg\"\n"
            + "                        },\n"
            + "                        \"name\": \"艾德·斯克林\",\n"
            + "                        \"id\": \"1329130\"\n"
            + "                    }\n"
            + "                ],\n"
            + "                \"collect_count\": 13944,\n"
            + "                \"original_title\": \"Deadpool\",\n"
            + "                \"subtype\": \"movie\",\n"
            + "                \"directors\": [\n"
            + "                    {\n"
            + "                        \"alt\": \"http://movie.douban.com/celebrity/1324984/\",\n"
            + "                        \"avatars\": {\n"
            + "                            \"small\": \"https://img3.doubanio.com/img/celebrity/small/1450493407.05"
            + ".jpg\",\n"
            + "                            \"large\": \"https://img3.doubanio.com/img/celebrity/large/1450493407.05"
            + ".jpg\",\n"
            + "                            \"medium\": \"https://img3.doubanio.com/img/celebrity/medium/1450493407.05"
            + ".jpg\"\n"
            + "                        },\n"
            + "                        \"name\": \"蒂姆·米勒\",\n"
            + "                        \"id\": \"1324984\"\n"
            + "                    }\n"
            + "                ],\n"
            + "                \"year\": \"2016\",\n"
            + "                \"images\": {\n"
            + "                    \"small\": \"https://img1.doubanio"
            + ".com/view/movie_poster_cover/ipst/public/p2309264172.jpg\",\n"
            + "                    \"large\": \"https://img1.doubanio"
            + ".com/view/movie_poster_cover/lpst/public/p2309264172.jpg\",\n"
            + "                    \"medium\": \"https://img1.doubanio"
            + ".com/view/movie_poster_cover/spst/public/p2309264172.jpg\"\n"
            + "                },\n"
            + "                \"alt\": \"http://movie.douban.com/subject/3718279/\",\n"
            + "                \"id\": \"3718279\"\n"
            + "            }\n"
            + "        },\n"
            + "        {\n"
            + "            \"box\": 10668000,\n"
            + "            \"new\": false,\n"
            + "            \"rank\": 4,\n"
            + "            \"subject\": {\n"
            + "                \"rating\": {\n"
            + "                    \"max\": 10,\n"
            + "                    \"average\": 6.1,\n"
            + "                    \"stars\": \"30\",\n"
            + "                    \"min\": 0\n"
            + "                },\n"
            + "                \"genres\": [\n"
            + "                    \"动作\",\n"
            + "                    \"犯罪\",\n"
            + "                    \"惊悚\"\n"
            + "                ],\n"
            + "                \"title\": \"伦敦陷落\",\n"
            + "                \"casts\": [\n"
            + "                    {\n"
            + "                        \"alt\": \"http://movie.douban.com/celebrity/1040500/\",\n"
            + "                        \"avatars\": {\n"
            + "                            \"small\": \"https://img3.doubanio.com/img/celebrity/small/406.jpg\",\n"
            + "                            \"large\": \"https://img3.doubanio.com/img/celebrity/large/406.jpg\",\n"
            + "                            \"medium\": \"https://img3.doubanio.com/img/celebrity/medium/406.jpg\"\n"
            + "                        },\n"
            + "                        \"name\": \"杰拉德·巴特勒\",\n"
            + "                        \"id\": \"1040500\"\n"
            + "                    },\n"
            + "                    {\n"
            + "                        \"alt\": \"http://movie.douban.com/celebrity/1053577/\",\n"
            + "                        \"avatars\": {\n"
            + "                            \"small\": \"https://img1.doubanio.com/img/celebrity/small/522.jpg\",\n"
            + "                            \"large\": \"https://img1.doubanio.com/img/celebrity/large/522.jpg\",\n"
            + "                            \"medium\": \"https://img1.doubanio.com/img/celebrity/medium/522.jpg\"\n"
            + "                        },\n"
            + "                        \"name\": \"艾伦·艾克哈特\",\n"
            + "                        \"id\": \"1053577\"\n"
            + "                    },\n"
            + "                    {\n"
            + "                        \"alt\": \"http://movie.douban.com/celebrity/1054534/\",\n"
            + "                        \"avatars\": {\n"
            + "                            \"small\": \"https://img1.doubanio.com/img/celebrity/small/34642.jpg\",\n"
            + "                            \"large\": \"https://img1.doubanio.com/img/celebrity/large/34642.jpg\",\n"
            + "                            \"medium\": \"https://img1.doubanio.com/img/celebrity/medium/34642.jpg\"\n"
            + "                        },\n"
            + "                        \"name\": \"摩根·弗里曼\",\n"
            + "                        \"id\": \"1054534\"\n"
            + "                    }\n"
            + "                ],\n"
            + "                \"collect_count\": 686,\n"
            + "                \"original_title\": \"London Has Fallen\",\n"
            + "                \"subtype\": \"movie\",\n"
            + "                \"directors\": [\n"
            + "                    {\n"
            + "                        \"alt\": \"http://movie.douban.com/celebrity/1317990/\",\n"
            + "                        \"avatars\": {\n"
            + "                            \"small\": \"https://img1.doubanio.com/img/celebrity/small/42004.jpg\",\n"
            + "                            \"large\": \"https://img1.doubanio.com/img/celebrity/large/42004.jpg\",\n"
            + "                            \"medium\": \"https://img1.doubanio.com/img/celebrity/medium/42004.jpg\"\n"
            + "                        },\n"
            + "                        \"name\": \"巴巴克·纳加非\",\n"
            + "                        \"id\": \"1317990\"\n"
            + "                    }\n"
            + "                ],\n"
            + "                \"year\": \"2016\",\n"
            + "                \"images\": {\n"
            + "                    \"small\": \"https://img3.doubanio"
            + ".com/view/movie_poster_cover/ipst/public/p2324133970.jpg\",\n"
            + "                    \"large\": \"https://img3.doubanio"
            + ".com/view/movie_poster_cover/lpst/public/p2324133970.jpg\",\n"
            + "                    \"medium\": \"https://img3.doubanio"
            + ".com/view/movie_poster_cover/spst/public/p2324133970.jpg\"\n"
            + "                },\n"
            + "                \"alt\": \"http://movie.douban.com/subject/25757186/\",\n"
            + "                \"id\": \"25757186\"\n"
            + "            }\n"
            + "        },\n"
            + "        {\n"
            + "            \"box\": 4600000,\n"
            + "            \"new\": false,\n"
            + "            \"rank\": 5,\n"
            + "            \"subject\": {\n"
            + "                \"rating\": {\n"
            + "                    \"max\": 10,\n"
            + "                    \"average\": 7,\n"
            + "                    \"stars\": \"35\",\n"
            + "                    \"min\": 0\n"
            + "                },\n"
            + "                \"genres\": [\n"
            + "                    \"喜剧\",\n"
            + "                    \"战争\"\n"
            + "                ],\n"
            + "                \"title\": \"威士忌、探戈、狐步舞\",\n"
            + "                \"casts\": [\n"
            + "                    {\n"
            + "                        \"alt\": \"http://movie.douban.com/celebrity/1044730/\",\n"
            + "                        \"avatars\": {\n"
            + "                            \"small\": \"https://img1.doubanio.com/img/celebrity/small/14493.jpg\",\n"
            + "                            \"large\": \"https://img1.doubanio.com/img/celebrity/large/14493.jpg\",\n"
            + "                            \"medium\": \"https://img1.doubanio.com/img/celebrity/medium/14493.jpg\"\n"
            + "                        },\n"
            + "                        \"name\": \"蒂娜·菲\",\n"
            + "                        \"id\": \"1044730\"\n"
            + "                    },\n"
            + "                    {\n"
            + "                        \"alt\": \"http://movie.douban.com/celebrity/1272303/\",\n"
            + "                        \"avatars\": {\n"
            + "                            \"small\": \"https://img1.doubanio.com/img/celebrity/small/1389939796.3"
            + ".jpg\",\n"
            + "                            \"large\": \"https://img1.doubanio.com/img/celebrity/large/1389939796.3"
            + ".jpg\",\n"
            + "                            \"medium\": \"https://img1.doubanio.com/img/celebrity/medium/1389939796.3"
            + ".jpg\"\n"
            + "                        },\n"
            + "                        \"name\": \"玛格特·罗比\",\n"
            + "                        \"id\": \"1272303\"\n"
            + "                    },\n"
            + "                    {\n"
            + "                        \"alt\": \"http://movie.douban.com/celebrity/1049612/\",\n"
            + "                        \"avatars\": {\n"
            + "                            \"small\": \"https://img1.doubanio.com/img/celebrity/small/35443.jpg\",\n"
            + "                            \"large\": \"https://img1.doubanio.com/img/celebrity/large/35443.jpg\",\n"
            + "                            \"medium\": \"https://img1.doubanio.com/img/celebrity/medium/35443.jpg\"\n"
            + "                        },\n"
            + "                        \"name\": \"马丁·弗瑞曼\",\n"
            + "                        \"id\": \"1049612\"\n"
            + "                    }\n"
            + "                ],\n"
            + "                \"collect_count\": 59,\n"
            + "                \"original_title\": \"Whiskey Tango Foxtrot\",\n"
            + "                \"subtype\": \"movie\",\n"
            + "                \"directors\": [\n"
            + "                    {\n"
            + "                        \"alt\": \"http://movie.douban.com/celebrity/1317347/\",\n"
            + "                        \"avatars\": {\n"
            + "                            \"small\": \"https://img1.doubanio.com/img/celebrity/small/46967.jpg\",\n"
            + "                            \"large\": \"https://img1.doubanio.com/img/celebrity/large/46967.jpg\",\n"
            + "                            \"medium\": \"https://img1.doubanio.com/img/celebrity/medium/46967.jpg\"\n"
            + "                        },\n"
            + "                        \"name\": \"格伦·费卡拉\",\n"
            + "                        \"id\": \"1317347\"\n"
            + "                    },\n"
            + "                    {\n"
            + "                        \"alt\": \"http://movie.douban.com/celebrity/1317350/\",\n"
            + "                        \"avatars\": {\n"
            + "                            \"small\": \"https://img3.doubanio.com/img/celebrity/small/46966.jpg\",\n"
            + "                            \"large\": \"https://img3.doubanio.com/img/celebrity/large/46966.jpg\",\n"
            + "                            \"medium\": \"https://img3.doubanio.com/img/celebrity/medium/46966.jpg\"\n"
            + "                        },\n"
            + "                        \"name\": \"约翰·里夸\",\n"
            + "                        \"id\": \"1317350\"\n"
            + "                    }\n"
            + "                ],\n"
            + "                \"year\": \"2016\",\n"
            + "                \"images\": {\n"
            + "                    \"small\": \"https://img3.doubanio"
            + ".com/view/movie_poster_cover/ipst/public/p2322044335.jpg\",\n"
            + "                    \"large\": \"https://img3.doubanio"
            + ".com/view/movie_poster_cover/lpst/public/p2322044335.jpg\",\n"
            + "                    \"medium\": \"https://img3.doubanio"
            + ".com/view/movie_poster_cover/spst/public/p2322044335.jpg\"\n"
            + "                },\n"
            + "                \"alt\": \"http://movie.douban.com/subject/26296905/\",\n"
            + "                \"id\": \"26296905\"\n"
            + "            }\n"
            + "        },\n"
            + "        {\n"
            + "            \"box\": 4150000,\n"
            + "            \"new\": true,\n"
            + "            \"rank\": 6,\n"
            + "            \"subject\": {\n"
            + "                \"rating\": {\n"
            + "                    \"max\": 10,\n"
            + "                    \"average\": 0,\n"
            + "                    \"stars\": \"00\",\n"
            + "                    \"min\": 0\n"
            + "                },\n"
            + "                \"genres\": [\n"
            + "                    \"喜剧\",\n"
            + "                    \"爱情\"\n"
            + "                ],\n"
            + "                \"title\": \"佳偶天成\",\n"
            + "                \"casts\": [\n"
            + "                    {\n"
            + "                        \"alt\": \"http://movie.douban.com/celebrity/1253316/\",\n"
            + "                        \"avatars\": {\n"
            + "                            \"small\": \"https://img1.doubanio.com/img/celebrity/small/1457968025.63"
            + ".jpg\",\n"
            + "                            \"large\": \"https://img1.doubanio.com/img/celebrity/large/1457968025.63"
            + ".jpg\",\n"
            + "                            \"medium\": \"https://img1.doubanio.com/img/celebrity/medium/1457968025.63"
            + ".jpg\"\n"
            + "                        },\n"
            + "                        \"name\": \"特伦斯·詹金斯\",\n"
            + "                        \"id\": \"1253316\"\n"
            + "                    },\n"
            + "                    {\n"
            + "                        \"alt\": \"http://movie.douban.com/celebrity/1049912/\",\n"
            + "                        \"avatars\": {\n"
            + "                            \"small\": \"https://img1.doubanio.com/img/celebrity/small/45583.jpg\",\n"
            + "                            \"large\": \"https://img1.doubanio.com/img/celebrity/large/45583.jpg\",\n"
            + "                            \"medium\": \"https://img1.doubanio.com/img/celebrity/medium/45583.jpg\"\n"
            + "                        },\n"
            + "                        \"name\": \"凯茜·温图拉\",\n"
            + "                        \"id\": \"1049912\"\n"
            + "                    },\n"
            + "                    {\n"
            + "                        \"alt\": \"http://movie.douban.com/celebrity/1009305/\",\n"
            + "                        \"avatars\": {\n"
            + "                            \"small\": \"https://img1.doubanio.com/img/celebrity/small/7598.jpg\",\n"
            + "                            \"large\": \"https://img1.doubanio.com/img/celebrity/large/7598.jpg\",\n"
            + "                            \"medium\": \"https://img1.doubanio.com/img/celebrity/medium/7598.jpg\"\n"
            + "                        },\n"
            + "                        \"name\": \"唐纳德·法森\",\n"
            + "                        \"id\": \"1009305\"\n"
            + "                    }\n"
            + "                ],\n"
            + "                \"collect_count\": 3,\n"
            + "                \"original_title\": \"The Perfect Match\",\n"
            + "                \"subtype\": \"movie\",\n"
            + "                \"directors\": [\n"
            + "                    {\n"
            + "                        \"alt\": \"http://movie.douban.com/celebrity/1301138/\",\n"
            + "                        \"avatars\": {\n"
            + "                            \"small\": \"https://img3.doubanio.com/img/celebrity/small/1457967724.25"
            + ".jpg\",\n"
            + "                            \"large\": \"https://img3.doubanio.com/img/celebrity/large/1457967724.25"
            + ".jpg\",\n"
            + "                            \"medium\": \"https://img3.doubanio.com/img/celebrity/medium/1457967724.25"
            + ".jpg\"\n"
            + "                        },\n"
            + "                        \"name\": \"比勒·沃道夫\",\n"
            + "                        \"id\": \"1301138\"\n"
            + "                    }\n"
            + "                ],\n"
            + "                \"year\": \"2016\",\n"
            + "                \"images\": {\n"
            + "                    \"small\": \"https://img1.doubanio"
            + ".com/view/movie_poster_cover/ipst/public/p2311179423.jpg\",\n"
            + "                    \"large\": \"https://img1.doubanio"
            + ".com/view/movie_poster_cover/lpst/public/p2311179423.jpg\",\n"
            + "                    \"medium\": \"https://img1.doubanio"
            + ".com/view/movie_poster_cover/spst/public/p2311179423.jpg\"\n"
            + "                },\n"
            + "                \"alt\": \"http://movie.douban.com/subject/26710681/\",\n"
            + "                \"id\": \"26710681\"\n"
            + "            }\n"
            + "        },\n"
            + "        {\n"
            + "            \"box\": 3404000,\n"
            + "            \"new\": true,\n"
            + "            \"rank\": 7,\n"
            + "            \"subject\": {\n"
            + "                \"rating\": {\n"
            + "                    \"max\": 10,\n"
            + "                    \"average\": 0,\n"
            + "                    \"stars\": \"00\",\n"
            + "                    \"min\": 0\n"
            + "                },\n"
            + "                \"genres\": [\n"
            + "                    \"剧情\"\n"
            + "                ],\n"
            + "                \"title\": \"耶稣基督：走出埃及\",\n"
            + "                \"casts\": [\n"
            + "                    {\n"
            + "                        \"alt\": \"http://movie.douban.com/celebrity/1355647/\",\n"
            + "                        \"avatars\": {\n"
            + "                            \"small\": \"https://img1.doubanio.com/img/celebrity/small/1458118806.64"
            + ".jpg\",\n"
            + "                            \"large\": \"https://img1.doubanio.com/img/celebrity/large/1458118806.64"
            + ".jpg\",\n"
            + "                            \"medium\": \"https://img1.doubanio.com/img/celebrity/medium/1458118806.64"
            + ".jpg\"\n"
            + "                        },\n"
            + "                        \"name\": \"亚当·格里夫斯-尼尔\",\n"
            + "                        \"id\": \"1355647\"\n"
            + "                    },\n"
            + "                    {\n"
            + "                        \"alt\": \"http://movie.douban.com/celebrity/1355675/\",\n"
            + "                        \"avatars\": {\n"
            + "                            \"small\": \"https://img3.doubanio.com/img/celebrity/small/1458117034.21"
            + ".jpg\",\n"
            + "                            \"large\": \"https://img3.doubanio.com/img/celebrity/large/1458117034.21"
            + ".jpg\",\n"
            + "                            \"medium\": \"https://img3.doubanio.com/img/celebrity/medium/1458117034.21"
            + ".jpg\"\n"
            + "                        },\n"
            + "                        \"name\": \"莎拉·拉扎罗\",\n"
            + "                        \"id\": \"1355675\"\n"
            + "                    },\n"
            + "                    {\n"
            + "                        \"alt\": \"http://movie.douban.com/celebrity/1163496/\",\n"
            + "                        \"avatars\": {\n"
            + "                            \"small\": \"https://img1.doubanio.com/img/celebrity/small/1458119204.59"
            + ".jpg\",\n"
            + "                            \"large\": \"https://img1.doubanio.com/img/celebrity/large/1458119204.59"
            + ".jpg\",\n"
            + "                            \"medium\": \"https://img1.doubanio.com/img/celebrity/medium/1458119204.59"
            + ".jpg\"\n"
            + "                        },\n"
            + "                        \"name\": \"文森特·沃尔什\",\n"
            + "                        \"id\": \"1163496\"\n"
            + "                    }\n"
            + "                ],\n"
            + "                \"collect_count\": 3,\n"
            + "                \"original_title\": \"The Young Messiah\",\n"
            + "                \"subtype\": \"movie\",\n"
            + "                \"directors\": [\n"
            + "                    {\n"
            + "                        \"alt\": \"http://movie.douban.com/celebrity/1050348/\",\n"
            + "                        \"avatars\": {\n"
            + "                            \"small\": \"https://img1.doubanio.com/img/celebrity/small/4292.jpg\",\n"
            + "                            \"large\": \"https://img1.doubanio.com/img/celebrity/large/4292.jpg\",\n"
            + "                            \"medium\": \"https://img1.doubanio.com/img/celebrity/medium/4292.jpg\"\n"
            + "                        },\n"
            + "                        \"name\": \"赛勒斯·诺拉斯特\",\n"
            + "                        \"id\": \"1050348\"\n"
            + "                    }\n"
            + "                ],\n"
            + "                \"year\": \"2016\",\n"
            + "                \"images\": {\n"
            + "                    \"small\": \"https://img3.doubanio"
            + ".com/view/movie_poster_cover/ipst/public/p2276807365.jpg\",\n"
            + "                    \"large\": \"https://img3.doubanio"
            + ".com/view/movie_poster_cover/lpst/public/p2276807365.jpg\",\n"
            + "                    \"medium\": \"https://img3.doubanio"
            + ".com/view/movie_poster_cover/spst/public/p2276807365.jpg\"\n"
            + "                },\n"
            + "                \"alt\": \"http://movie.douban.com/subject/3071546/\",\n"
            + "                \"id\": \"3071546\"\n"
            + "            }\n"
            + "        },\n"
            + "        {\n"
            + "            \"box\": 3150000,\n"
            + "            \"new\": true,\n"
            + "            \"rank\": 8,\n"
            + "            \"subject\": {\n"
            + "                \"rating\": {\n"
            + "                    \"max\": 10,\n"
            + "                    \"average\": 7.7,\n"
            + "                    \"stars\": \"40\",\n"
            + "                    \"min\": 0\n"
            + "                },\n"
            + "                \"genres\": [\n"
            + "                    \"喜剧\",\n"
            + "                    \"动作\"\n"
            + "                ],\n"
            + "                \"title\": \"王牌贱谍：格林斯比\",\n"
            + "                \"casts\": [\n"
            + "                    {\n"
            + "                        \"alt\": \"http://movie.douban.com/celebrity/1027161/\",\n"
            + "                        \"avatars\": {\n"
            + "                            \"small\": \"https://img1.doubanio.com/img/celebrity/small/1727.jpg\",\n"
            + "                            \"large\": \"https://img1.doubanio.com/img/celebrity/large/1727.jpg\",\n"
            + "                            \"medium\": \"https://img1.doubanio.com/img/celebrity/medium/1727.jpg\"\n"
            + "                        },\n"
            + "                        \"name\": \"萨莎·拜伦·科恩\",\n"
            + "                        \"id\": \"1027161\"\n"
            + "                    },\n"
            + "                    {\n"
            + "                        \"alt\": \"http://movie.douban.com/celebrity/1274374/\",\n"
            + "                        \"avatars\": {\n"
            + "                            \"small\": \"https://img1.doubanio.com/img/celebrity/small/27592.jpg\",\n"
            + "                            \"large\": \"https://img1.doubanio.com/img/celebrity/large/27592.jpg\",\n"
            + "                            \"medium\": \"https://img1.doubanio.com/img/celebrity/medium/27592.jpg\"\n"
            + "                        },\n"
            + "                        \"name\": \"马克·斯特朗\",\n"
            + "                        \"id\": \"1274374\"\n"
            + "                    },\n"
            + "                    {\n"
            + "                        \"alt\": \"http://movie.douban.com/celebrity/1041001/\",\n"
            + "                        \"avatars\": {\n"
            + "                            \"small\": \"https://img1.doubanio.com/img/celebrity/small/437.jpg\",\n"
            + "                            \"large\": \"https://img1.doubanio.com/img/celebrity/large/437.jpg\",\n"
            + "                            \"medium\": \"https://img1.doubanio.com/img/celebrity/medium/437.jpg\"\n"
            + "                        },\n"
            + "                        \"name\": \"艾拉·菲舍尔\",\n"
            + "                        \"id\": \"1041001\"\n"
            + "                    }\n"
            + "                ],\n"
            + "                \"collect_count\": 242,\n"
            + "                \"original_title\": \"The Brothers Grimsby\",\n"
            + "                \"subtype\": \"movie\",\n"
            + "                \"directors\": [\n"
            + "                    {\n"
            + "                        \"alt\": \"http://movie.douban.com/celebrity/1018091/\",\n"
            + "                        \"avatars\": {\n"
            + "                            \"small\": \"https://img3.doubanio.com/img/celebrity/small/28036.jpg\",\n"
            + "                            \"large\": \"https://img3.doubanio.com/img/celebrity/large/28036.jpg\",\n"
            + "                            \"medium\": \"https://img3.doubanio.com/img/celebrity/medium/28036.jpg\"\n"
            + "                        },\n"
            + "                        \"name\": \"路易斯·莱特里尔\",\n"
            + "                        \"id\": \"1018091\"\n"
            + "                    }\n"
            + "                ],\n"
            + "                \"year\": \"2016\",\n"
            + "                \"images\": {\n"
            + "                    \"small\": \"https://img1.doubanio"
            + ".com/view/movie_poster_cover/ipst/public/p2293944453.jpg\",\n"
            + "                    \"large\": \"https://img1.doubanio"
            + ".com/view/movie_poster_cover/lpst/public/p2293944453.jpg\",\n"
            + "                    \"medium\": \"https://img1.doubanio"
            + ".com/view/movie_poster_cover/spst/public/p2293944453.jpg\"\n"
            + "                },\n"
            + "                \"alt\": \"http://movie.douban.com/subject/25830732/\",\n"
            + "                \"id\": \"25830732\"\n"
            + "            }\n"
            + "        },\n"
            + "        {\n"
            + "            \"box\": 2500000,\n"
            + "            \"new\": false,\n"
            + "            \"rank\": 9,\n"
            + "            \"subject\": {\n"
            + "                \"rating\": {\n"
            + "                    \"max\": 10,\n"
            + "                    \"average\": 6.8,\n"
            + "                    \"stars\": \"35\",\n"
            + "                    \"min\": 0\n"
            + "                },\n"
            + "                \"genres\": [\n"
            + "                    \"动作\",\n"
            + "                    \"奇幻\",\n"
            + "                    \"冒险\"\n"
            + "                ],\n"
            + "                \"title\": \"神战：权力之眼\",\n"
            + "                \"casts\": [\n"
            + "                    {\n"
            + "                        \"alt\": \"http://movie.douban.com/celebrity/1076051/\",\n"
            + "                        \"avatars\": {\n"
            + "                            \"small\": \"https://img3.doubanio.com/img/celebrity/small/1368693740.25"
            + ".jpg\",\n"
            + "                            \"large\": \"https://img3.doubanio.com/img/celebrity/large/1368693740.25"
            + ".jpg\",\n"
            + "                            \"medium\": \"https://img3.doubanio.com/img/celebrity/medium/1368693740.25"
            + ".jpg\"\n"
            + "                        },\n"
            + "                        \"name\": \"尼古拉·科斯特-瓦尔道\",\n"
            + "                        \"id\": \"1076051\"\n"
            + "                    },\n"
            + "                    {\n"
            + "                        \"alt\": \"http://movie.douban.com/celebrity/1325896/\",\n"
            + "                        \"avatars\": {\n"
            + "                            \"small\": \"https://img1.doubanio.com/img/celebrity/small/1410910563.02"
            + ".jpg\",\n"
            + "                            \"large\": \"https://img1.doubanio.com/img/celebrity/large/1410910563.02"
            + ".jpg\",\n"
            + "                            \"medium\": \"https://img1.doubanio.com/img/celebrity/medium/1410910563.02"
            + ".jpg\"\n"
            + "                        },\n"
            + "                        \"name\": \"布伦顿·思韦茨\",\n"
            + "                        \"id\": \"1325896\"\n"
            + "                    },\n"
            + "                    {\n"
            + "                        \"alt\": \"http://movie.douban.com/celebrity/1040500/\",\n"
            + "                        \"avatars\": {\n"
            + "                            \"small\": \"https://img3.doubanio.com/img/celebrity/small/406.jpg\",\n"
            + "                            \"large\": \"https://img3.doubanio.com/img/celebrity/large/406.jpg\",\n"
            + "                            \"medium\": \"https://img3.doubanio.com/img/celebrity/medium/406.jpg\"\n"
            + "                        },\n"
            + "                        \"name\": \"杰拉德·巴特勒\",\n"
            + "                        \"id\": \"1040500\"\n"
            + "                    }\n"
            + "                ],\n"
            + "                \"collect_count\": 10528,\n"
            + "                \"original_title\": \"Gods of Egypt\",\n"
            + "                \"subtype\": \"movie\",\n"
            + "                \"directors\": [\n"
            + "                    {\n"
            + "                        \"alt\": \"http://movie.douban.com/celebrity/1027346/\",\n"
            + "                        \"avatars\": {\n"
            + "                            \"small\": \"https://img3.doubanio.com/img/celebrity/small/9385.jpg\",\n"
            + "                            \"large\": \"https://img3.doubanio.com/img/celebrity/large/9385.jpg\",\n"
            + "                            \"medium\": \"https://img3.doubanio.com/img/celebrity/medium/9385.jpg\"\n"
            + "                        },\n"
            + "                        \"name\": \"亚历克斯·普罗亚斯\",\n"
            + "                        \"id\": \"1027346\"\n"
            + "                    }\n"
            + "                ],\n"
            + "                \"year\": \"2016\",\n"
            + "                \"images\": {\n"
            + "                    \"small\": \"https://img3.doubanio"
            + ".com/view/movie_poster_cover/ipst/public/p2324130130.jpg\",\n"
            + "                    \"large\": \"https://img3.doubanio"
            + ".com/view/movie_poster_cover/lpst/public/p2324130130.jpg\",\n"
            + "                    \"medium\": \"https://img3.doubanio"
            + ".com/view/movie_poster_cover/spst/public/p2324130130.jpg\"\n"
            + "                },\n"
            + "                \"alt\": \"http://movie.douban.com/subject/26662345/\",\n"
            + "                \"id\": \"26662345\"\n"
            + "            }\n"
            + "        },\n"
            + "        {\n"
            + "            \"box\": 2250000,\n"
            + "            \"new\": false,\n"
            + "            \"rank\": 10,\n"
            + "            \"subject\": {\n"
            + "                \"rating\": {\n"
            + "                    \"max\": 10,\n"
            + "                    \"average\": 6.1,\n"
            + "                    \"stars\": \"30\",\n"
            + "                    \"min\": 0\n"
            + "                },\n"
            + "                \"genres\": [\n"
            + "                    \"剧情\",\n"
            + "                    \"动作\",\n"
            + "                    \"悬疑\"\n"
            + "                ],\n"
            + "                \"title\": \"复活\",\n"
            + "                \"casts\": [\n"
            + "                    {\n"
            + "                        \"alt\": \"http://movie.douban.com/celebrity/1047983/\",\n"
            + "                        \"avatars\": {\n"
            + "                            \"small\": \"https://img1.doubanio.com/img/celebrity/small/50433.jpg\",\n"
            + "                            \"large\": \"https://img1.doubanio.com/img/celebrity/large/50433.jpg\",\n"
            + "                            \"medium\": \"https://img1.doubanio.com/img/celebrity/medium/50433.jpg\"\n"
            + "                        },\n"
            + "                        \"name\": \"约瑟夫·费因斯\",\n"
            + "                        \"id\": \"1047983\"\n"
            + "                    },\n"
            + "                    {\n"
            + "                        \"alt\": \"http://movie.douban.com/celebrity/1049488/\",\n"
            + "                        \"avatars\": {\n"
            + "                            \"small\": \"https://img1.doubanio.com/img/celebrity/small/33698.jpg\",\n"
            + "                            \"large\": \"https://img1.doubanio.com/img/celebrity/large/33698.jpg\",\n"
            + "                            \"medium\": \"https://img1.doubanio.com/img/celebrity/medium/33698.jpg\"\n"
            + "                        },\n"
            + "                        \"name\": \"汤姆·费尔顿\",\n"
            + "                        \"id\": \"1049488\"\n"
            + "                    },\n"
            + "                    {\n"
            + "                        \"alt\": \"http://movie.douban.com/celebrity/1041217/\",\n"
            + "                        \"avatars\": {\n"
            + "                            \"small\": \"https://img3.doubanio.com/img/celebrity/small/9555.jpg\",\n"
            + "                            \"large\": \"https://img3.doubanio.com/img/celebrity/large/9555.jpg\",\n"
            + "                            \"medium\": \"https://img3.doubanio.com/img/celebrity/medium/9555.jpg\"\n"
            + "                        },\n"
            + "                        \"name\": \"彼得·弗斯\",\n"
            + "                        \"id\": \"1041217\"\n"
            + "                    }\n"
            + "                ],\n"
            + "                \"collect_count\": 46,\n"
            + "                \"original_title\": \"Risen\",\n"
            + "                \"subtype\": \"movie\",\n"
            + "                \"directors\": [\n"
            + "                    {\n"
            + "                        \"alt\": \"http://movie.douban.com/celebrity/1014056/\",\n"
            + "                        \"avatars\": {\n"
            + "                            \"small\": \"https://img1.doubanio.com/img/celebrity/small/1368590042.59"
            + ".jpg\",\n"
            + "                            \"large\": \"https://img1.doubanio.com/img/celebrity/large/1368590042.59"
            + ".jpg\",\n"
            + "                            \"medium\": \"https://img1.doubanio.com/img/celebrity/medium/1368590042.59"
            + ".jpg\"\n"
            + "                        },\n"
            + "                        \"name\": \"凯文·雷诺兹\",\n"
            + "                        \"id\": \"1014056\"\n"
            + "                    }\n"
            + "                ],\n"
            + "                \"year\": \"2016\",\n"
            + "                \"images\": {\n"
            + "                    \"small\": \"https://img1.doubanio"
            + ".com/view/movie_poster_cover/ipst/public/p2321522114.jpg\",\n"
            + "                    \"large\": \"https://img1.doubanio"
            + ".com/view/movie_poster_cover/lpst/public/p2321522114.jpg\",\n"
            + "                    \"medium\": \"https://img1.doubanio"
            + ".com/view/movie_poster_cover/spst/public/p2321522114.jpg\"\n"
            + "                },\n"
            + "                \"alt\": \"http://movie.douban.com/subject/25755444/\",\n"
            + "                \"id\": \"25755444\"\n"
            + "            }\n"
            + "        },\n"
            + "        {\n"
            + "            \"box\": 2000000,\n"
            + "            \"new\": false,\n"
            + "            \"rank\": 11,\n"
            + "            \"subject\": {\n"
            + "                \"rating\": {\n"
            + "                    \"max\": 10,\n"
            + "                    \"average\": 8,\n"
            + "                    \"stars\": \"40\",\n"
            + "                    \"min\": 0\n"
            + "                },\n"
            + "                \"genres\": [\n"
            + "                    \"剧情\",\n"
            + "                    \"惊悚\",\n"
            + "                    \"冒险\"\n"
            + "                ],\n"
            + "                \"title\": \"荒野猎人\",\n"
            + "                \"casts\": [\n"
            + "                    {\n"
            + "                        \"alt\": \"http://movie.douban.com/celebrity/1041029/\",\n"
            + "                        \"avatars\": {\n"
            + "                            \"small\": \"https://img3.doubanio.com/img/celebrity/small/470.jpg\",\n"
            + "                            \"large\": \"https://img3.doubanio.com/img/celebrity/large/470.jpg\",\n"
            + "                            \"medium\": \"https://img3.doubanio.com/img/celebrity/medium/470.jpg\"\n"
            + "                        },\n"
            + "                        \"name\": \"莱昂纳多·迪卡普里奥\",\n"
            + "                        \"id\": \"1041029\"\n"
            + "                    },\n"
            + "                    {\n"
            + "                        \"alt\": \"http://movie.douban.com/celebrity/1049489/\",\n"
            + "                        \"avatars\": {\n"
            + "                            \"small\": \"https://img3.doubanio.com/img/celebrity/small/5110.jpg\",\n"
            + "                            \"large\": \"https://img3.doubanio.com/img/celebrity/large/5110.jpg\",\n"
            + "                            \"medium\": \"https://img3.doubanio.com/img/celebrity/medium/5110.jpg\"\n"
            + "                        },\n"
            + "                        \"name\": \"汤姆·哈迪\",\n"
            + "                        \"id\": \"1049489\"\n"
            + "                    },\n"
            + "                    {\n"
            + "                        \"alt\": \"http://movie.douban.com/celebrity/1004692/\",\n"
            + "                        \"avatars\": {\n"
            + "                            \"small\": \"https://img3.doubanio.com/img/celebrity/small/1439047149.05"
            + ".jpg\",\n"
            + "                            \"large\": \"https://img3.doubanio.com/img/celebrity/large/1439047149.05"
            + ".jpg\",\n"
            + "                            \"medium\": \"https://img3.doubanio.com/img/celebrity/medium/1439047149.05"
            + ".jpg\"\n"
            + "                        },\n"
            + "                        \"name\": \"威尔·保尔特\",\n"
            + "                        \"id\": \"1004692\"\n"
            + "                    }\n"
            + "                ],\n"
            + "                \"collect_count\": 47278,\n"
            + "                \"original_title\": \"The Revenant\",\n"
            + "                \"subtype\": \"movie\",\n"
            + "                \"directors\": [\n"
            + "                    {\n"
            + "                        \"alt\": \"http://movie.douban.com/celebrity/1054403/\",\n"
            + "                        \"avatars\": {\n"
            + "                            \"small\": \"https://img3.doubanio.com/img/celebrity/small/570.jpg\",\n"
            + "                            \"large\": \"https://img3.doubanio.com/img/celebrity/large/570.jpg\",\n"
            + "                            \"medium\": \"https://img3.doubanio.com/img/celebrity/medium/570.jpg\"\n"
            + "                        },\n"
            + "                        \"name\": \"亚利桑德罗·冈萨雷斯·伊纳里多\",\n"
            + "                        \"id\": \"1054403\"\n"
            + "                    }\n"
            + "                ],\n"
            + "                \"year\": \"2015\",\n"
            + "                \"images\": {\n"
            + "                    \"small\": \"https://img1.doubanio"
            + ".com/view/movie_poster_cover/ipst/public/p2323258429.jpg\",\n"
            + "                    \"large\": \"https://img1.doubanio"
            + ".com/view/movie_poster_cover/lpst/public/p2323258429.jpg\",\n"
            + "                    \"medium\": \"https://img1.doubanio"
            + ".com/view/movie_poster_cover/spst/public/p2323258429.jpg\"\n"
            + "                },\n"
            + "                \"alt\": \"http://movie.douban.com/subject/5327268/\",\n"
            + "                \"id\": \"5327268\"\n"
            + "            }\n"
            + "        }\n"
            + "    ],\n"
            + "    \"title\": \"豆瓣电影北美票房榜\"\n"
            + "}";
}